/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bib.h"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

livre *lvr = NULL;
int result;

void print_list(livre * head) {
    livre * current = head;

    while (current != NULL) {
        printf("{%d, %s, %s, %s, %s, %d ,%f}\n",current->num,
												current->titre,
												current->acteur,
												current->editeur,
												current->anneePub,
												current->nbrExemplaire,
												current->prix);
        current = current->next;
    }
}
void print_livre(livre * livre) {
	if(livre == NULL){
		printf("Livre No Found \n");
	}
	printf("{%d, %s, %s, %s, %s, %d ,%f}\n",livre->num,
											livre->titre,
											livre->acteur,
											livre->editeur,
											livre->anneePub,
											livre->nbrExemplaire,
											livre->prix);
}

livre *faire_livre(int num,char *titre, char *acteur, char *editeur, char* annePub, int nbrExemplaire, float prix)
{
    livre *lvr;

    lvr = (livre*)malloc(sizeof(livre));
    if (lvr == NULL)
        return NULL;
    lvr->num = num;
	lvr->titre = titre;
	lvr->acteur = acteur;
	lvr->editeur = editeur;
	lvr->anneePub = annePub;
	lvr->nbrExemplaire = nbrExemplaire;
	lvr->prix = prix;
    lvr->next = NULL;
    return lvr;
}

void append(struct livre** head_ref, livre new_data)
{
    struct livre* new_node = (struct livre*) malloc(sizeof(struct livre));
 
    struct livre *last = lvr; 
	new_node->num = new_data.num;
  	new_node->titre = (char*)malloc(30);
  	new_node->acteur = (char*)malloc(30);
  	new_node->editeur = (char*)malloc(30);
  	new_node->anneePub = (char*)malloc(30);
	strcpy(new_node->titre, new_data.titre);
	strcpy(new_node->acteur, new_data.acteur);
	strcpy(new_node->editeur, new_data.editeur);
	strcpy(new_node->anneePub, new_data.anneePub);
	new_node->nbrExemplaire = new_data.nbrExemplaire;
	new_node->prix = new_data.prix;
    new_node->next = NULL;
 
    if (*head_ref == NULL)
    {
       *head_ref = new_node;
       return;
    } 
    while (last->next != NULL)
        last = last->next;
  
    last->next = new_node;
    return;   
}

void *
init_livre_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
    struct livre* new_node = (struct livre*) malloc(sizeof(struct livre));

	livre *one,*two,*three,*four,*five,*six;
	one = faire_livre(1,"djabir","djabir","editeur 1","2020/04/04",5,10.22);
	two = faire_livre(2,"omar","omar","editeur 2","2020/04/04",10,20);
	three = faire_livre(3,"manel","manel","editeur 3","2020/04/04",20,40);
	four = faire_livre(4,"nouha","nouha","editeur 4","2022/04/04",40,80);
	five = faire_livre(5,"tigrine","nouha","editeur 4","2022/04/04",40,80);
	six = faire_livre(6,"tigrine","nouha","editeur 4","2022/04/04",40,80);
	
	append(&lvr,*one);
	append(&lvr,*two);
	append(&lvr,*three);
	append(&lvr,*four);
	append(&lvr,*five);
	append(&lvr,*six);

	return (void *) &result;
}

void *
ajoute_livre_1_svc(livre *argp, struct svc_req *rqstp)
{
	static char * result;

	append(&lvr,*argp);

	return (void *) &result;
}

void *
modifier_livre_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

void *
supprimer_livre_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

    struct livre *temp = lvr, *prev;
 
    if (temp != NULL && temp->titre == *argp) {
        lvr = temp->next;
        free(temp);
        return (void *) &result;
    }
 
    while (temp != NULL && temp->titre != *argp) {
        prev = temp;
        temp = temp->next;
    }
 
    if (temp == NULL)
        return (void *) &result;

    prev->next = temp->next;
 
    free(temp);

	return (void *) &result;
}

livre *
consulter_livre_1_svc(char **argp, struct svc_req *rqstp)
{
	struct livre* current = lvr;
	if(lvr == NULL) {
		return NULL;
	}
	
	while(strcmp(current->titre,*argp)) {
		
		if(current->next == NULL) {
			return NULL;
		} else {
			current = current->next;
		}
	}

	return current;
}

livre *
consulter_tout_1_svc(void *argp, struct svc_req *rqstp)
{
	static livre  result;

	result = *lvr;

	return &result;
}

livre *
afficher_livre_1_svc(char **argp, struct svc_req *rqstp)
{
	struct livre* current = lvr;
	static livre*  result;
	
	while(current->next != NULL) {
		if (!strcmp(current->acteur,*argp)) append(&result,*current);
		current = current->next;
	}
	return result;
}

float *
prix_total_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;

	livre *ptr;

    ptr = lvr;
    result = 0;
    while (ptr != NULL) {
        result += ptr->prix;
        ptr = ptr->next;
    }

	return &result;
}
