/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "livre.h"
#include <mysql/mysql.h>
#include <stdio.h>
#include <string.h>

int *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("init_1_svc \n");
    MYSQL* conn = mysql_init(NULL);

	//connection à notre base de données Livre
    if (mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0) == NULL) {
        printf("Unable to connect with MySQL server\n");
        mysql_close(conn);
		result = 1;
        return &result;
    }
	//creation de la table Livre
	mysql_query(conn, "CREATE TABLE Livre(num INT NOT NULL PRIMARY KEY, titre VARCHAR(30), auteur VARCHAR(30), editeur VARCHAR(30),anneePub DATE,nbrExemplaire INT,prix FLOAT)");

	//inserer quelques livres
    mysql_query(conn, "insert into Livre values(1,'Archi M2','djabir','kahlouche','1992-02-01', 5 , 12)");

	mysql_query(conn, "insert into Livre values(2,'Data Structure','zaza','zaza','1998-08-02', 9 , 258)");

	mysql_query(conn, "insert into Livre values(3,'Deep Learning','gaceb','test','1999-12-21', 3 , 10)");

    mysql_close(conn);

	result = 1;
	return &result;
}

int *
ajouter_1_svc(livre *argp, struct svc_req *rqstp)
{
	static int  result;
	char query[300];
	MYSQL* conn = mysql_init(NULL);
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);

	/*
		INSERT INTO Livre values(%d,'%s','%s','%s','%s', %d , %f)
	*/
	//sprintf c'est pour inserer les elements dans l'ordre et les enregistrer dans la variable query
	sprintf(query, "insert into Livre values(%d,'%s','%s','%s','%s', %d , %f)",
						argp->num,
						argp->titre,
						argp->auteur,
						argp->editeur,
						argp->anneePub,
						argp->nbrExmplr,
						argp->prix);

	//mysql_query pour executer les requetes sql dans la connection conn qui est connecter à notre BDD
	// elle return NULL dans le cas d'echec
	if (mysql_query(conn, query)) {
        mysql_close(conn);

		result = 0;
        return &result;
    }

	result = 1;
	return &result;
}

int *
modifier_1_svc(livre *argp, struct svc_req *rqstp)
{
	static int  result;
	char query[300];

    MYSQL* conn = mysql_init(NULL);
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);

	/*
		Update livre set titre = '%s',
			auteur = '%s',
			editeur = '%s', 
			anneePub = '%s',
			nbrExemplaire = %d , 
			prix = %f 
			where num = %d",
	*/

	//la requete pour modifier un livre
	sprintf(query, "update Livre set titre = '%s',auteur = '%s',editeur = '%s', anneePub = '%s', nbrExemplaire = %d , prix = %f where num = %d",
						argp->titre,
						argp->auteur,
						argp->editeur,
						argp->anneePub,
						argp->nbrExmplr,
						argp->prix,
						argp->num);
	if (mysql_query(conn, query)) {
        mysql_close(conn);

		result = 0;
        return &result;
    }

	result = 1;
	return &result;
}

int *
supprimer_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	char query[300];

    MYSQL* conn = mysql_init(NULL);
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);

	/*
		DELETE FROM Livre WHERE num=%d
	*/
	sprintf(query, "DELETE FROM Livre WHERE num=%d",*argp);
	if (mysql_query(conn, query)) {
        mysql_close(conn);

		result = 0;
        return &result;
    }

    mysql_close(conn);
	result = 1;
	return &result;
}

livre *
consulter_1_svc(int *argp, struct svc_req *rqstp)
{
	static livre  result;
	char query[300];
    int data;
	MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);
	
	/*
		SELECT * FROM Livre WHERE num = %d
	*/
    sprintf(query, "SELECT * FROM Livre WHERE num = %d", *argp);
    mysql_query(conn, query);

	// enregistrer le resultat dans rs (rs c'est un MYSQL_RES pour Resultat)
    MYSQL_RES* rs = mysql_store_result(conn);

	//record c'est pour lire les elements d'une lignes
	//on lis chaque ligne de notre resultat
	//et on l'enregistre dans record pour le lire ensuite
    while (record = mysql_fetch_row(rs)) {
		livre lv1;
		lv1.titre = (char*)malloc(30);
		lv1.auteur = (char*)malloc(30);
		lv1.editeur = (char*)malloc(30);
		lv1.anneePub = (char*)malloc(30);

		lv1.num = atoi(record[0]);
		strcpy(lv1.titre , record[1]);
		strcpy(lv1.auteur , record[2]);
		strcpy(lv1.editeur , record[3]);
		strcpy(lv1.anneePub , record[4]);
		lv1.nbrExmplr = atoi(record[5]);
		lv1.prix = atoll(record[6]);

		result = lv1;
    }
    mysql_close(conn);
	return &result;
}

livres *
afficher_1_svc(void *argp, struct svc_req *rqstp)
{
	static livres  result;
	int num,i = 0;


    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);

    mysql_query(conn, "SELECT * FROM Livre");

    MYSQL_RES* rs = mysql_store_result(conn);

	// (int)mysql_num_rows(rs) to parse it to type int because he come in int_64
	num = (int)mysql_num_rows(rs);

	// saisir la taille de la nouvelle liste pour copier le resultat dedans
	result.livres_len = num;

	//allouer un espace
	result.livres_val = malloc(num*sizeof(struct livre));

    while (record = mysql_fetch_row(rs)) {
		
		livre lv1;
		lv1.titre = (char*)malloc(30);
		lv1.auteur = (char*)malloc(30);
		lv1.editeur = (char*)malloc(30);
		lv1.anneePub = (char*)malloc(30);

		// atoi c'est pour transferer type string en entier car le resultat de MYSQL est tjr un string
		lv1.num = atoi(record[0]);
		strcpy(lv1.titre , record[1]);
		strcpy(lv1.auteur , record[2]);
		strcpy(lv1.editeur , record[3]);
		strcpy(lv1.anneePub , record[4]);
		lv1.nbrExmplr = atoi(record[5]);

		//atoll c'est pour type string vers float
		lv1.prix = atoll(record[6]);

		result.livres_val[i] = lv1;

		i++;
    }
    mysql_close(conn);
	return &result;
}

livres *
auteur_1_svc(char **argp, struct svc_req *rqstp)
{
	static livres  result;
	char query[300];
    int data;
	int num,i = 0;

	/*
		La meme chose que la fonction consulter toute les livres juste que ici c'est par auteur
	*/

    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);

    sprintf(query, "SELECT * FROM Livre WHERE auteur = '%s'", *argp);
    mysql_query(conn, query);

    MYSQL_RES* rs = mysql_store_result(conn);

	num = (int)mysql_num_rows(rs);
	result.livres_len = num;
	result.livres_val = malloc(num*sizeof(struct livre));
    while (record = mysql_fetch_row(rs)) {
		livre lv1;
		lv1.titre = (char*)malloc(30);
		lv1.auteur = (char*)malloc(30);
		lv1.editeur = (char*)malloc(30);
		lv1.anneePub = (char*)malloc(30);

		lv1.num = atoi(record[0]);
		strcpy(lv1.titre , record[1]);
		strcpy(lv1.auteur , record[2]);
		strcpy(lv1.editeur , record[3]);
		strcpy(lv1.anneePub , record[4]);
		lv1.nbrExmplr = atoi(record[5]);
		lv1.prix = atoll(record[6]);

		result.livres_val[i] = lv1;

		i++;
    }
    mysql_close(conn);
	return &result;
}

float *
prix_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;
	float num;


    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, "localhost", "root", "papamama123", "Livre", 0, NULL, 0);

    mysql_query(conn, "SELECT * FROM Livre");

    MYSQL_RES* rs = mysql_store_result(conn);
    while (record = mysql_fetch_row(rs)) {
		//lire chaque ligne et le transfrer vers float
		num += atoll(record[6]);
    }
    mysql_close(conn);
	return &result;
}
