/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bib.h"
#include <mysql/mysql.h>
#include <stdio.h>
#include <string.h>
void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("init\n");
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";

    MYSQL* conn = mysql_init(NULL);

    if (conn == NULL) {
        printf("MySQL initialization failed");
        return (void *) &result;
    }

    if (mysql_real_connect(conn, server, username, password, database, 0, NULL, 0) == NULL) {
        printf("Unable to connect with MySQL server\n");
        mysql_close(conn);
        return (void *) &result;
    }

    if (mysql_query(conn, "CREATE TABLE Livre(num INT, titre VARCHAR(30), auteur VARCHAR(30), editeur VARCHAR(30),anneePub VARCHAR(16),nbrExemplaire INT,prix FLOAT)")) {
        printf("Unable to create database table in MyDb database\n");
        mysql_close(conn);
        return (void *) &result;
    }

    if (mysql_query(conn, "insert into Livre values(101,'djabir','djabir','djabir','1992/02/01', 4 , 10000)")) {
        printf("Unable to insert data into Employee table\n");
        mysql_close(conn);
        return (void *) &result;
    }

	if (mysql_query(conn, "insert into Livre values(102,'omar','omar','omar','1998/08/02', 4 , 258)")) {
        printf("Unable to insert data into Employee table\n");
        mysql_close(conn);
        return (void *) &result;
    }

	if (mysql_query(conn, "insert into Livre values(103,'hicham','hicham','hicham','1999/12/21', 9 , 10)")) {
        printf("Unable to insert data into Employee table\n");
        mysql_close(conn);
        return (void *) &result;
    }

    mysql_close(conn);

    printf("Data inserted successfully\n");


	return (void *) &result;
}

void *
ajouter_1_svc(livre *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("ajouter\n");
	printf("new -> {%d,%s,%s,%s,%s,%d,%.2f}\n",
						argp->num,
						argp->titre,
						argp->auteur,
						argp->editeur,
						argp->anneePub,
						argp->nbrExemplaire,
						argp->prix);
	
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
	char query[300];

    MYSQL* conn = mysql_init(NULL);
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);
	sprintf(query, "insert into Livre values(%d,'%s','%s','%s','%s', %d , %f)",
						argp->num,
						argp->titre,
						argp->auteur,
						argp->editeur,
						argp->anneePub,
						argp->nbrExemplaire,
						argp->prix);
	if (mysql_query(conn, query)) {
        printf("Unable to insert data into Employee table\n");
        mysql_close(conn);
        return (void *) &result;
    }

    mysql_close(conn);

    printf("Data inserted successfully\n");

	return (void *) &result;
}

void *
modifier_1_svc(livre *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("modifier\n");
	printf("new -> {%d,%s,%s,%s,%s,%d,%.2f}\n",
						argp->num,
						argp->titre,
						argp->auteur,
						argp->editeur,
						argp->anneePub,
						argp->nbrExemplaire,
						argp->prix);
	
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
	char query[300];

    MYSQL* conn = mysql_init(NULL);
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);
	/*
	UPDATE Customers
	SET ContactName = 'Alfred Schmidt', City= 'Frankfurt'
	WHERE CustomerID = 1;
	*/
	sprintf(query, "update Livre set titre = '%s',auteur = '%s',editeur = '%s', anneePub = '%s', nbrExemplaire = %d , prix = %f where num = %d",
						argp->titre,
						argp->auteur,
						argp->editeur,
						argp->anneePub,
						argp->nbrExemplaire,
						argp->prix,
						argp->num);
	if (mysql_query(conn, query)) {
        printf("Unable to update data into Employee table\n");
        mysql_close(conn);
        return (void *) &result;
    }

	return (void *) &result;
}

void *
supprimer_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("supprimer\n");
	// DELETE FROM Customers WHERE CustomerName='Alfreds Futterkiste';
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
	char query[300];

    MYSQL* conn = mysql_init(NULL);
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);
	sprintf(query, "DELETE FROM Livre WHERE num=%d",*argp);
	if (mysql_query(conn, query)) {
        printf("Unable to delete data into Employee table\n");
        mysql_close(conn);
        return (void *) &result;
    }

    mysql_close(conn);

    printf("Data deleted successfully\n");

	return (void *) &result;
}

livre *
consulter_1_svc(int *argp, struct svc_req *rqstp)
{
	static livre  result;

	printf("cosulter\n");
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
    char query[300];
    int data;


    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);

    sprintf(query, "SELECT * FROM Livre WHERE num = %d", *argp);
    mysql_query(conn, query);

    MYSQL_RES* rs = mysql_store_result(conn);
    while (record = mysql_fetch_row(rs)) {
        printf("%s %s %s\n", record[0], record[1], record[2]);
    }
    mysql_close(conn);

	return &result;
}

livres *
afficher_1_svc(void *argp, struct svc_req *rqstp)
{
	static livres  result;

	printf("afficher\n");
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
	int num,i = 0;


    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);

    mysql_query(conn, "SELECT * FROM Livre");

    MYSQL_RES* rs = mysql_store_result(conn);

	printf("Vous avez %d\n",(int)mysql_num_rows(rs));
	num = (int)mysql_num_rows(rs);
	result.livres_len = num;
	result.livres_val = malloc(num*sizeof(struct livre));

    while (record = mysql_fetch_row(rs)) {
        printf("%d | %s %s %s %s %s %s %s\n",i, record[0], record[1], record[2], record[3], record[4], record[5],record[6]);
		livre lv1;
		lv1.titre = (char*)malloc(30);
		lv1.auteur = (char*)malloc(30);
		lv1.editeur = (char*)malloc(30);
		lv1.anneePub = (char*)malloc(30);

		lv1.num = atoi(record[0]);
		strcpy(lv1.titre , record[1]);
		strcpy(lv1.auteur , record[2]);
		strcpy(lv1.editeur , record[3]);
		strcpy(lv1.anneePub , record[4]);
		lv1.nbrExemplaire = atoi(record[5]);
		lv1.prix = atoll(record[6]);

		result.livres_val[i] = lv1;

		i++;
    }
    mysql_close(conn);

	return &result;
}

livres *
auteur_1_svc(char **argp, struct svc_req *rqstp)
{
	static livres  result;
	printf("auteur %s\n",*argp);
	
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
    char query[300];
    int data;
	int num,i = 0;


    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);

    sprintf(query, "SELECT * FROM Livre WHERE auteur = '%s'", *argp);
    mysql_query(conn, query);

    MYSQL_RES* rs = mysql_store_result(conn);

	printf("Vous avez %d\n",(int)mysql_num_rows(rs));
	num = (int)mysql_num_rows(rs);
	result.livres_len = num;
	result.livres_val = malloc(num*sizeof(struct livre));
    while (record = mysql_fetch_row(rs)) {
        printf("%d | %s %s %s %s %s %s %s\n",i, record[0], record[1], record[2], record[3], record[4], record[5],record[6]);
		livre lv1;
		lv1.titre = (char*)malloc(30);
		lv1.auteur = (char*)malloc(30);
		lv1.editeur = (char*)malloc(30);
		lv1.anneePub = (char*)malloc(30);

		lv1.num = atoi(record[0]);
		strcpy(lv1.titre , record[1]);
		strcpy(lv1.auteur , record[2]);
		strcpy(lv1.editeur , record[3]);
		strcpy(lv1.anneePub , record[4]);
		lv1.nbrExemplaire = atoi(record[5]);
		lv1.prix = atoll(record[6]);

		result.livres_val[i] = lv1;

		i++;
    }
    mysql_close(conn);
	
	return &result;
}

float *
prix_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("prix\n");
	printf("afficher\n");
	char server[16] = "localhost";
    char username[16] = "root";
    char password[16] = "papamama123";
    char database[16] = "test";
	float num;


    MYSQL* conn = mysql_init(NULL);
    MYSQL_ROW record;
    
    mysql_real_connect(conn, server, username, password, database, 0, NULL, 0);

    mysql_query(conn, "SELECT * FROM Livre");

    MYSQL_RES* rs = mysql_store_result(conn);
    while (record = mysql_fetch_row(rs)) {
		num += atoll(record[6]);
    }
	printf("Votre PRIX %.2f\n",num);
    mysql_close(conn);

	return &result;
}