/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bib.h"
#include <string.h>

livres lvr;

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	livre lv1,lv2,lv3;

	lv1.num = 1;
	lv1.titre = "djabir";
	lv1.auteur = "djabir";
	lv1.editeur = "djabir";
	lv1.anneePub = "1998/04/01";
	lv1.nbrExemplaire = 5;
	lv1.prix = 9.99;

	lv2.num = 2;
	lv2.titre = "omar";
	lv2.auteur = "omar";
	lv2.editeur = "omar";
	lv2.anneePub = "1998/03/21";
	lv2.nbrExemplaire = 10;
	lv2.prix = 19.99;

	lv3.num = 3;
	lv3.titre = "hicham";
	lv3.auteur = "omar";
	lv3.editeur = "hicham";
	lv3.anneePub = "1998/03/21";
	lv3.nbrExemplaire = 10;
	lv3.prix = 14.99;

	lvr.livres_len = 3;
	lvr.livres_val = malloc(3*sizeof(struct livre));

	lvr.livres_val[0] = lv1;
	lvr.livres_val[1] = lv2;
	lvr.livres_val[2] = lv3;

	return (void *) &result;
}

void *
ajouter_1_svc(livre *argp, struct svc_req *rqstp)
{
	static char * result;
	int length;
	livres temp;
	temp = lvr;
	
	livre lv1;
	lv1.titre = (char*)malloc(30);
	lv1.auteur = (char*)malloc(30);
	lv1.editeur = (char*)malloc(30);
	lv1.anneePub = (char*)malloc(30);

	lv1.num = argp->num;
	strcpy(lv1.titre , argp->titre);
	strcpy(lv1.auteur , argp->auteur);
	strcpy(lv1.editeur , argp->editeur);
	strcpy(lv1.anneePub , argp->anneePub);
	lv1.nbrExemplaire = argp->nbrExemplaire;
	lv1.prix = argp->prix;
	
	length = lvr.livres_len + 1;
	lvr.livres_len = length;
	lvr.livres_val = malloc(length * sizeof(struct livre));
	for(int i=0;i<length;i++)
	{
		lvr.livres_val[i] = temp.livres_val[i];
	}
	lvr.livres_val[length-1] = lv1;
	for(int i=0;i<lvr.livres_len;i++)
	{
		printf("new -> {%d,%s,%s,%s,%s,%d,%.2f}\n",
						lvr.livres_val[i].num,
						lvr.livres_val[i].titre,
						lvr.livres_val[i].auteur,
						lvr.livres_val[i].editeur,
						lvr.livres_val[i].anneePub,
						lvr.livres_val[i].nbrExemplaire,
						lvr.livres_val[i].prix);
	}

	return (void *) &result;
}

void *
modifier_1_svc(livre *argp, struct svc_req *rqstp)
{
	static char * result;
	livre lv1;
	lv1.titre = (char*)malloc(30);
	lv1.auteur = (char*)malloc(30);
	lv1.editeur = (char*)malloc(30);
	lv1.anneePub = (char*)malloc(30);

	lv1.num = argp->num;
	strcpy(lv1.titre , argp->titre);
	strcpy(lv1.auteur , argp->auteur);
	strcpy(lv1.editeur , argp->editeur);
	strcpy(lv1.anneePub , argp->anneePub);
	lv1.nbrExemplaire = argp->nbrExemplaire;
	lv1.prix = argp->prix;

	for(int i=0;i<lvr.livres_len;i++)
	{
		if(lvr.livres_val[i].num == lv1.num)
		{
			lvr.livres_val[i] = lv1;
		}
	}

	return (void *) &result;
}

void *
supprimer_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
	int index;
	/*
	 * insert server code here
	 for (c = position - 1; c < n - 1; c++)
         array[c] = array[c+1];
	 */
	for(int i=0;i<lvr.livres_len;i++)
	{
		if(strcmp(lvr.livres_val[i].auteur, *argp) == 0)
		{
			index = i;
		}
	}
	for(int i = index-1; i < lvr.livres_len - 1; i++)
		lvr.livres_val[i] = lvr.livres_val[i+1];

	lvr.livres_len = lvr.livres_len -1;

	return (void *) &result;
}

livre *
consulter_1_svc(char **argp, struct svc_req *rqstp)
{
	static livre  result;

	printf("le mot %s\n",*argp);
	for(int i=0;i<lvr.livres_len;i++)
	{
		if(strcmp(lvr.livres_val[i].titre, *argp) == 0)
		{
			result = lvr.livres_val[i];
		}
	}
	
	return &result;
}

livres *
afficher_1_svc(void *argp, struct svc_req *rqstp)
{
	static livres  result;

	result = lvr;

	return &result;
}

livres *
auteur_1_svc(char **argp, struct svc_req *rqstp)
{
	static livres  result,result_7;
	int num = 0,num2=0;
	printf("le mot %s\n",*argp);
	for(int i=0;i<lvr.livres_len;i++)
	{
		if(strcmp(lvr.livres_val[i].auteur, *argp) == 0)
		{
			printf("found -> {%d,%s,%s,%s,%s,%d,%.2f}\n",
						lvr.livres_val[i].num,
						lvr.livres_val[i].titre,
						lvr.livres_val[i].auteur,
						lvr.livres_val[i].editeur,
						lvr.livres_val[i].anneePub,
						lvr.livres_val[i].nbrExemplaire,
						lvr.livres_val[i].prix);
			num++;
		}
	}
	printf("On a touve %d\n",num);
	result_7.livres_len = num;
	result_7.livres_val = malloc(num*sizeof(struct livre));

	
	for(int i=0;i<lvr.livres_len;i++)
	{
		if(strcmp(lvr.livres_val[i].auteur, *argp) == 0)
		{
			result_7.livres_val[num2] = lvr.livres_val[i];
			num2++;
		}
	}
	
	for(int i=0;i<result_7.livres_len;i++)
	{
		printf("found -> {%d,%s,%s,%s,%s,%d,%.2f}\n",
						result_7.livres_val[i].num,
						result_7.livres_val[i].titre,
						result_7.livres_val[i].auteur,
						result_7.livres_val[i].editeur,
						result_7.livres_val[i].anneePub,
						result_7.livres_val[i].nbrExemplaire,
						result_7.livres_val[i].prix);
	}
	return &result_7;
}

float *
prix_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;

	for(int i=0;i<lvr.livres_len;i++)
	{
		result +=lvr.livres_val[i].prix;
	}
	return &result;
}
